import type { NextPage } from 'next'
import Head from 'next/head'
import { Container } from '../components/Container'
const Home: NextPage = () => {
  return (
    <Container>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className="flex gap-5 h-[600px] flex-col items-center justify-center w-full text-center px-3">
        <h1 className="text-5xl font-extrabold leading-tight md:text-6xl">
          Sheffield <span className="text-primary">Hallam</span> University
        </h1>
        <h2 className="text-3xl font-extrabold leading-tight md:text-4xl">
          The University of the <span className="text-secondary">future</span>
        </h2>
        <h3 className="text-2xl font-extrabold leading-tight xl:text-3xl text-primary">
          Apply today
        </h3>
        <div className="btn-group">
          <button className="btn btn-primary">Get Started</button>
          <button className="btn btn-secondary">Explore</button>
          <button className="btn">Open days</button>
        </div>
      </section>
    </Container>
  )
}

export default Home
