import type { NextPage } from 'next'
import Head from 'next/head'
import { Container } from '../components/Container'
import { BiSearchAlt } from 'react-icons/bi'
const Home: NextPage = () => {
  return (
    <Container>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className="flex gap-5 h-[600px] flex-col items-center justify-center w-full text-center px-3">
        <h1 className="text-5xl font-extrabold leading-tight md:text-6xl">
          Sheffield <span className="text-primary">Hallam</span> University
        </h1>
        <h2 className="text-3xl font-extrabold leading-tight md:text-4xl">
          The University of the <span className="text-secondary">future</span>
        </h2>
        <h3 className="text-2xl font-extrabold leading-tight xl:text-3xl text-primary">
          Apply today
        </h3>
        <div className="btn-group">
          <button className="btn btn-primary">Get Started</button>
          <button className="btn btn-secondary">Explore</button>
          <button className="btn">Open days</button>
        </div>
      </section>

      <section className="h-[300px] gap-5 flex-col flex items-center justify-center text-center">
        <h1 className="text-4xl font-extrabold leading-tight md:text-5xl text-secondary">
          Course Search
        </h1>

        {/* Search input */}
        <div className="w-1/2 form-control">
          <div className="input-group">
            <input
              type="text"
              placeholder="Search…"
              className="w-full input input-bordered"
            />
            <button className="btn btn-square">
              <BiSearchAlt className="w-6 h-6" />
            </button>
          </div>
        </div>
        {/* Search input ends*/}
      </section>
    </Container>
  )
}

export default Home
