import type { NextPage } from 'next'
import Head from 'next/head'
import { Container } from '../components/Container'
import { BiSearchAlt } from 'react-icons/bi'
import { CardContainer } from '../components/CardContainer'
import { Card } from '../components/Card'
const Home: NextPage = () => {
  return (
    <Container>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className="flex gap-5 h-[600px] flex-col items-center justify-center w-full text-center px-3">
        <h1 className="text-5xl font-extrabold leading-tight md:text-6xl">
          Sheffield <span className="text-primary">Hallam</span> University
        </h1>
        <h2 className="text-3xl font-extrabold leading-tight md:text-4xl">
          The University of the <span className="text-secondary">future</span>
        </h2>
        <h3 className="text-2xl font-extrabold leading-tight xl:text-3xl text-primary">
          Apply today
        </h3>
        <div className="btn-group">
          <button className="btn btn-primary">Get Started</button>
          <button className="btn btn-secondary">Explore</button>
          <button className="btn">Open days</button>
        </div>
      </section>

      <section className="h-[300px] gap-5 flex-col flex items-center justify-center text-center">
        <h1 className="text-4xl font-extrabold leading-tight md:text-5xl text-secondary">
          Course Search
        </h1>

        {/* Search input */}
        <div className="w-1/2 form-control">
          <div className="input-group">
            <input
              type="text"
              placeholder="Search…"
              className="w-full input input-bordered"
            />
            <button className="btn btn-square">
              <BiSearchAlt className="w-6 h-6" />
            </button>
          </div>
        </div>
        {/* Search input ends*/}
      </section>

      <section className="h-[600px] flex-col gap-5 px-4 flex items-center justify-center text-center">
        <h1 className="text-4xl font-extrabold leading-tight md:text-5xl">
          Research at <span className="text-primary">Hallam</span>
        </h1>
        <h2 className="text-2xl font-extrabold leading-tight md:text-3xl">
          We bring <span className="text-secondary">knowledge</span> to life
          with innovative, real-world research.
        </h2>
        {/* mobile  */}
        <div className="btn-group-vertical btn-group md:hidden">
          <button className="btn btn-secondary">REF 2021 results</button>
          <button className="btn btn-secondary">Research areas</button>
          <button className="btn btn-secondary">Research degrees</button>
          <button className="btn btn-secondary">Research in action</button>
          <button className="btn btn-secondary">People</button>
        </div>
        {/* desktop  */}
        <div className="hidden btn-group md:block">
          <button className="btn btn-secondary">REF 2021 results</button>
          <button className="btn btn-secondary">Research areas</button>
          <button className="btn btn-secondary">Research degrees</button>
          <button className="btn btn-secondary">Research in action</button>
          <button className="btn btn-secondary">People</button>
        </div>
      </section>

      <section className="flex flex-col gap-5 px-4 py-3 text-center">
        <h1 className="text-4xl font-extrabold leading-tight md:text-5xl">
          For applicants
        </h1>
        <CardContainer>
          <Card
            src="/images/card-hero-1.jpeg"
            alt=""
            title="Explore Sheffield"
            body="Our city is scenic, creative and super friendly. You're going to love it"
            href=""
          />
          <Card
            src="/images/card-hero-2.jpeg"
            alt=""
            title="Why choose us?"
            body="Award-winning teaching, world-class facilities and dedicated support"
            href=""
          />
          <Card
            src="/images/card-hero-3.jpeg"
            alt=""
            title="Accommodation"
            body="We'll find you a place to live in your first year guaranteed!"
            href=""
          />
        </CardContainer>
      </section>

      <section className="flex flex-col gap-5 px-4 py-3 text-center">
        <h1 className="text-4xl font-extrabold leading-tight md:text-5xl">
          News
        </h1>
        <CardContainer>
          <Card
            src="/images/card-hero-1.jpeg"
            alt=""
            title="Explore Sheffield"
            body="Our city is scenic, creative and super friendly. You're going to love it"
            href=""
          />
          <Card
            src="/images/card-hero-2.jpeg"
            alt=""
            title="Why choose us?"
            body="Award-winning teaching, world-class facilities and dedicated support"
            href=""
          />
          <Card
            src="/images/card-hero-3.jpeg"
            alt=""
            title="Accommodation"
            body="We'll find you a place to live in your first year guaranteed!"
            href=""
          />
        </CardContainer>
      </section>
      <section className="flex flex-col gap-5 px-4 py-3 mb-5 text-center">
        <h1 className="text-4xl font-extrabold leading-tight md:text-5xl">
          About
        </h1>
        <CardContainer>
          <Card
            src="/images/card-hero-1.jpeg"
            alt=""
            title="Explore Sheffield"
            body="Our city is scenic, creative and super friendly. You're going to love it"
            href=""
          />
          <Card
            src="/images/card-hero-2.jpeg"
            alt=""
            title="Why choose us?"
            body="Award-winning teaching, world-class facilities and dedicated support"
            href=""
          />
          <Card
            src="/images/card-hero-3.jpeg"
            alt=""
            title="Accommodation"
            body="We'll find you a place to live in your first year guaranteed!"
            href=""
          />
        </CardContainer>
      </section>
    </Container>
  )
}

export default Home
